### ISSUE TITLE
empty dashboard

### ISSUE THREAD

**Issue by solune** [cookielab/terraform-kubernetes-dashboard#2]
Hello,

I get the token from `kubectl describe secret kubernetes-dashboard-token-6wkvf -n kubernetes-dashboard`.
The authentication is successfull but all items are empty with an example error :
`storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:kubernetes-dashboard:kubernetes-dashboard" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope`

Is there a post install config to do ?
regards

**Comment by Vrtak-CZ** [comment]
Hi, where did you get `kubernetes-dashboard-token-6wkvf` secret? You will need to create service account for accessing dashboard. for example:

```terraform
resource "kubernetes_service_account" "dashboard_admin" {
  metadata {
    name = "dashboard-admin"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "dashboard_admin" {
  metadata {
    name = "dashboard-admin"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind = "ClusterRole"
    name = "cluster-admin"
  }

  subject {
    kind = "ServiceAccount"
    name = kubernetes_service_account.dashboard_admin.metadata.0.name
    namespace = kubernetes_service_account.dashboard_admin.metadata.0.namespace
  }
}

data "kubernetes_secret" "dashboard_admin" {
  metadata {
    name = kubernetes_service_account.dashboard_admin.default_secret_name
    namespace = kubernetes_service_account.dashboard_admin.metadata.0.namespace
  }
}

output "dashboard_admin_token" {
  value = data.kubernetes_secret.dashboard_admin.data.token
}
```

**Comment by solune** [comment]
thanks
